
version: "3.8"

services:
  # ==========================================
  # LOCALSTACK - Servicios AWS Locales
  # ==========================================
  localstack:
    profiles: ["green"]
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # Servicios externos
    environment:
      # Servicios AWS a activar
      - SERVICES=s3,dynamodb,sqs,cloudwatch,logs

      # Configuración básica
      - DEBUG=1 
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localhost

      # Persistencia de datos
      - PERSISTENCE=1
    volumes:
      - localstack-data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

  # Proxy inverso - punto de entrada único
  nginx:
    image: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      
    depends_on:
      - blue-app
      #- green-app
    restart: unless-stopped

  # Aplicación Blue (versión actual en producción)
  blue-app:
    build: .
    environment:
      - CURRENT_STAGE=1
      - USE_STATIC_DASHBOARD=true
      - NODE_ENV=production
    expose:
      - "3000"
    ports:
      - "3001:3000"
    restart: unless-stopped

  # Aplicación Green (nueva versión con LocalStack)
  green-app:
    build: .    
    profiles: ["green"]
    environment:
      - CURRENT_STAGE=2
      - USE_STATIC_DASHBOARD=false
      - NODE_ENV=production
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack
    expose:
      - "3000"
    ports:
      - "3002:3000"
    restart: unless-stopped

volumes:
  localstack-data: {}

