
services:
  # Proxy inverso - punto de entrada único
  nginx:
    image: nginx:alpine
    ports:
      - "81:81"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      #- ./nginx-default-empty.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - blue-app
      - green-app
    networks:
      - la-huella-network_app
    restart: unless-stopped

  # Aplicación Blue (versión actual en producción)
  blue-app:
    build: .
    environment:
      - CURRENT_STAGE=1
      - USE_STATIC_DASHBOARD=true
      - NODE_ENV=production
    expose:
      - "3000"
    ports:
      - "3001:3000"
    networks:
      - la-huella-network_app
    restart: unless-stopped

  # Aplicación Green (nueva versión con LocalStack)
  green-app:
    build: .
    environment:
      - CURRENT_STAGE=2
      - USE_STATIC_DASHBOARD=false
      - NODE_ENV=production
      - AWS_ENDPOINT_URL=http://LocalStack:4566
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    expose:
      - "3000"
    ports:
      - "3002:3000"
    networks:
      - la-huella-network_app
    restart: unless-stopped

networks:
  la-huella-network_app:
    external: true
    name: eu-devops-6-localstack_la-huella-network